### ISSUE TITLE
檔案管理與SEO問題

### ISSUE THREAD

**Issue by Inndy** [sunset1995/hackgen#1]
- index.html 和 pages 全部都應該要進 master
- content 不要切到別的檔案，除非用 link，不然對 SEO 傷害很大，搜尋引擎會找不到任何內容

**Comment by Inndy** [comment]
pages 的問題可以用 `gulp-file-include` 解決

請參考：
https://github.com/Inndy/inndy.github.io/blob/src/app/index.html#L50
https://github.com/Inndy/inndy.github.io/blob/src/gulpfile.js#L29-L31

**Comment by sunset1995** [comment]
感謝！
已使用 gulp-file-include 將所有內容直接放入 index.html
